"""Governed provider-neutral remote Git contracts."""

from .mcp import GIT_REMOTE_MCP_TOOLS, GitRemoteMcpToolHandler
from .models import (
    BranchInfo,
    BranchPage,
    CreateBranchRequest,
    CreatePullRequestRequest,
    DiffFile,
    GetBranchRequest,
    GetPullRequestRequest,
    GetRemoteDiffRequest,
    GetRepositoryRequest,
    GitErrorCode,
    GitToolResult,
    ListBranchesRequest,
    PullRequestInfo,
    RemoteDiff,
    RepositoryInfo,
    TrustedGitContext,
    UpdateBranchRequest,
    UpdatePullRequestRequest,
)
from .ports import GitProviderContext, GitProviderFailure, GitToolAuditEvent, RemoteGitProvider
from .service import GitAuditError, GitCancelled, GovernedRemoteGitService

__all__ = [
    "BranchInfo",
    "BranchPage",
    "CreateBranchRequest",
    "CreatePullRequestRequest",
    "DiffFile",
    "GIT_REMOTE_MCP_TOOLS",
    "GetBranchRequest",
    "GetPullRequestRequest",
    "GetRemoteDiffRequest",
    "GetRepositoryRequest",
    "GitAuditError",
    "GitCancelled",
    "GitErrorCode",
    "GitProviderContext",
    "GitProviderFailure",
    "GitRemoteMcpToolHandler",
    "GitToolAuditEvent",
    "GitToolResult",
    "GovernedRemoteGitService",
    "ListBranchesRequest",
    "PullRequestInfo",
    "RemoteDiff",
    "RemoteGitProvider",
    "RepositoryInfo",
    "TrustedGitContext",
    "UpdateBranchRequest",
    "UpdatePullRequestRequest",
]
